'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(n='arrow')=>`<svg aria-hidden="true"><use href="#${n}"/></svg>`;
const {countries,ideas}=window.AMANU;const params=new URLSearchParams(location.search);
const motion=matchMedia('(prefers-reduced-motion: reduce)');
const alternateTeamPortrait=$('.portrait-two');if(alternateTeamPortrait)alternateTeamPortrait.src='assets/team-portrait-3.webp';
window.addEventListener('message',event=>{const frame=$('#pac-frame');if(!frame||event.source!==frame.contentWindow||event.origin!==location.origin||event.data?.type!=='amanu-pac-height')return;const height=Number(event.data.height);if(Number.isFinite(height))frame.style.height=Math.min(10000,Math.max(520,height+24))+'px'});
const leadDialog=$('#lead-dialog'),contentDialog=$('#content-dialog');let lastFocus=null;
function showDialog(d){if(d.open)return;lastFocus=document.activeElement;d.showModal();d.scrollTop=0}
function content(markup){$('#content-body').innerHTML=markup;showDialog(contentDialog)}
$$('dialog').forEach(d=>{d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()});d.addEventListener('close',()=>{if(lastFocus?.isConnected)lastFocus.focus()})});
function openLead(context='Подбор путешествия',comment=''){if(contentDialog.open)contentDialog.close();$('#lead-content').hidden=false;$('#lead-success').hidden=true;$('#lead-form').reset();$('#form-error').textContent='';$('#lead-context').value=context;$('#lead-comment').value=comment||context;showDialog(leadDialog)}
function validateLead(form){const digits=form.elements.phone.value.replace(/\D/g,'');if(digits.length<10||digits.length>15){form.elements.phone.focus();return 'Проверьте телефон: укажите от 10 до 15 цифр.'}if(form.elements.name.value.trim().length<2){form.elements.name.focus();return 'Пожалуйста, укажите ваше имя.'}return ''}
let formErrorPending=params.get('formState')==='error';
$('#lead-form').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,error=validateLead(f);$('#form-error').textContent=error;if(error)return;const submit=f.querySelector('[type=submit]'),label=submit.innerHTML;submit.disabled=true;submit.textContent='Проверяем форму…';setTimeout(()=>{submit.disabled=false;submit.innerHTML=label;if(formErrorPending){formErrorPending=false;$('#form-error').textContent='Демонстрация ошибки доставки. Данные остались в форме — нажмите «Подобрать тур» ещё раз. Реальная отправка не выполняется.';return}$('#lead-content').hidden=true;$('#lead-success').hidden=false;f.reset();leadDialog.scrollTop=0;$('#lead-success [data-close]').focus()},400)});
$$('.inline-lead').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const error=validateLead(f),status=f.querySelector('.inline-form-status');status.textContent=error||'Демонстрация завершена. На рабочем сайте менеджер свяжется для подтверждения цены и мест. Сейчас заявка не отправлена.';if(!error)f.reset()}));
document.addEventListener('click',e=>{const b=e.target.closest('[data-close],[data-lead],[data-idea],[data-route],[data-info],[data-gallery]');if(!b)return;if(b.hasAttribute('data-close'))b.closest('dialog')?.close();else if(b.dataset.lead!==undefined)openLead(b.dataset.lead);else if(b.dataset.route)location.href=b.dataset.route;else if(b.dataset.idea)location.href=b.dataset.idea==='cruises'?'cruises.html':`idea-${b.dataset.idea}.html`;else if(b.dataset.gallery){content(`<h2 id="content-title" class="gallery-title">${esc(b.querySelector('img')?.alt||'Фотография')}</h2><img class="gallery-full" src="${esc(b.dataset.gallery)}" alt="${esc(b.querySelector('img')?.alt||'Фотография')}">`)}else if(b.dataset.info==='whatsapp'){window.open('https://wa.me/78007700840','_blank','noopener')}else if(['privacy','consent'].includes(b.dataset.info)){content('<p class="eyebrow">Локальный прототип</p><h2 id="content-title">Обработка данных</h2><p>Демонстрационная форма не отправляет и не сохраняет данные.</p><a class="text-link" href="consent.html">Открыть документ ↗</a>')}else{location.href=({team:'about',prototype:'review'}[b.dataset.info]||b.dataset.info)+'.html'}});
const menu=$('#navigation'),menuToggle=$('#menu-toggle');if(menu&&!menu.querySelector('.nav-lead')){const navLead=document.createElement('button');navLead.className='nav-lead';navLead.dataset.lead='Помощь с выбором путешествия';navLead.textContent='Поможем выбрать путешествие';menu.append(navLead)}function closeMenu(){menu.classList.remove('open');menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-label','Открыть меню')}
menuToggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open));menuToggle.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню')});menu.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();closeGuests()}});document.addEventListener('click',e=>{if(!e.target.closest('.header'))closeMenu();if(!e.target.closest('#guest-popover,#guest-toggle'))closeGuests()});window.addEventListener('scroll',()=>$('#header')?.classList.toggle('scrolled',scrollY>30),{passive:true});
const pageName=location.pathname.split('/').pop()||'index.html';$$('#navigation a').forEach(a=>{if(a.getAttribute('href')===pageName)a.setAttribute('aria-current','page')});
const catalogToggle=$('#catalog-toggle'),catalogDropdown=$('#catalog-dropdown');
function closeCatalog(){if(!catalogDropdown)return;catalogDropdown.hidden=true;catalogToggle.setAttribute('aria-expanded','false')}
catalogToggle?.addEventListener('click',()=>{catalogDropdown.hidden=!catalogDropdown.hidden;catalogToggle.setAttribute('aria-expanded',String(!catalogDropdown.hidden))});
document.addEventListener('click',e=>{if(!e.target.closest('.nav-catalog'))closeCatalog()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&catalogDropdown&&!catalogDropdown.hidden){closeCatalog();catalogToggle.focus()}});
catalogToggle?.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();catalogDropdown.hidden=false;catalogToggle.setAttribute('aria-expanded','true');catalogDropdown.querySelector('a').focus()}});
document.querySelector('.nav-catalog')?.addEventListener('focusout',e=>{if(!e.currentTarget.contains(e.relatedTarget))closeCatalog()});
if($('#map-markers')){let active='maldives';function selectCountry(key){active=key;const d=countries[key];for(const [id,value]of Object.entries({'destination-title':d.name,'destination-region':d.region,'destination-description':d.description,'destination-tag':d.tags}))$('#'+id).textContent=value;$('#destination-image').src='assets/'+d.image;$('#destination-image').alt=d.alt;$$('[data-country]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.country===key)))}Object.entries(countries).forEach(([key,d])=>{const marker=document.createElement('button');marker.className='map-marker';marker.dataset.country=key;marker.style.left=`${(d.lon+180)/360*100}%`;marker.style.top=`${(85-d.lat)/145*100}%`;marker.setAttribute('aria-label',d.name+' — открыть направление');marker.innerHTML=`<span>${d.name}</span>`;marker.addEventListener('mouseenter',()=>selectCountry(key));marker.addEventListener('focus',()=>selectCountry(key));marker.addEventListener('click',()=>location.href=`country-${key}.html`);$('#map-markers').append(marker);const chip=document.createElement('button');chip.className='country-chip';chip.dataset.country=key;chip.textContent=d.name;chip.addEventListener('click',()=>selectCountry(key));$('#country-list').append(chip)});$('#destination-open').addEventListener('click',()=>location.href=`country-${active}.html`);selectCountry(active)}
$('#country-search')?.addEventListener('input',e=>{const term=e.target.value.trim().toLocaleLowerCase('ru'),cards=$$('[data-filter-name]');cards.forEach(c=>c.hidden=!c.dataset.filterName.includes(term));$('#country-empty').hidden=cards.some(c=>!c.hidden)});
let adults=2,children=0;const guestToggle=$('#guest-toggle'),guestPopover=$('#guest-popover');function closeGuests(){if(!guestPopover)return;guestPopover.hidden=true;guestToggle.setAttribute('aria-expanded','false')}
const dateString=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
if($('#search-form')){guestToggle.addEventListener('click',()=>{guestPopover.hidden=!guestPopover.hidden;guestToggle.setAttribute('aria-expanded',String(!guestPopover.hidden))});$$('[data-counter]').forEach(b=>b.addEventListener('click',()=>{const delta=Number(b.dataset.delta);if(b.dataset.counter==='adults')adults=Math.max(1,Math.min(8,adults+delta));else children=Math.max(0,Math.min(4,children+delta));$('#adult-count').textContent=adults;$('#child-count').textContent=children;guestToggle.innerHTML=`${adults} ${adults===1?'взрослый':'взрослых'}${children?' + '+children+' дет.':''} <span aria-hidden="true">⌄</span>`;$$('[data-counter]').forEach(x=>{const value=x.dataset.counter==='adults'?adults:children;x.disabled=Number(x.dataset.delta)<0?value<=(x.dataset.counter==='adults'?1:0):value>=(x.dataset.counter==='adults'?8:4)})}));$('#guests-done').addEventListener('click',()=>{closeGuests();guestToggle.focus()});const today=new Date();$('#travel-date').min=dateString(today);const initial=new Date(today);initial.setDate(today.getDate()+21);$('#travel-date').value=dateString(initial);
let product='tours';const initialFields=['departure','destination','nights'].map(id=>$('#'+id).innerHTML);function changeProduct(key){product=key;const cruiseEntry=document.querySelector('.cruise-hero-entry');if(cruiseEntry){cruiseEntry.hidden=key!=='cruises';document.querySelector('.search-fields').hidden=key==='cruises';}closeGuests();$$('[data-product]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.product===key));b.tabIndex=b.dataset.product===key?0:-1});$('#search-form').setAttribute('aria-labelledby',`tab-${key}`);$('#departure-label').textContent=key==='cruises'?'Порт отправления':'Город вылета';$('#nights-label').textContent=key==='cruises'?'Лайнер':'Продолжительность';$('#departure').innerHTML=key==='cruises'?'<option>Любой порт</option><option>Стамбул</option><option>Дубай</option><option>Барселона</option>':initialFields[0];$('#destination').innerHTML=key==='cruises'?'<option value="all">Любой регион</option><option value="med">Средиземноморье</option><option value="gulf">Персидский залив</option><option value="asia">Азия</option>':initialFields[1];$('#nights').innerHTML=key==='cruises'?'<option value="all">Любой лайнер</option><option>MSC Euribia</option><option>MSC World Europa</option><option>Costa Toscana</option>':initialFields[2];$('.search-submit span').textContent=key==='cruises'?'Найти круизы':key==='excursions'?'Найти маршруты':'Найти туры'}$$('[data-product]').forEach(b=>{b.addEventListener('click',()=>changeProduct(b.dataset.product));b.addEventListener('keydown',e=>{const tabs=$$('[data-product]');let i=tabs.indexOf(b);if(e.key==='ArrowRight')i=(i+1)%tabs.length;else if(e.key==='ArrowLeft')i=(i+tabs.length-1)%tabs.length;else return;e.preventDefault();changeProduct(tabs[i].dataset.product);tabs[i].focus()})});$('#search-form').addEventListener('submit',e=>{e.preventDefault();const query=new URLSearchParams({region:$('#destination').value,date:$('#travel-date').value,departure:$('#departure').value,adults:String(adults),children:String(children)});query.set(product==='cruises'?'ship':'nights',$('#nights').value);location.href=({tours:'search',cruises:'cruises',excursions:'excursions'}[product])+'.html?'+query})}
if($('#live-tour-search')){const summary=[];for(const key of ['departure','region','date','nights','adults','children']){const value=params.get(key);if(value&&value!=='all'&&value!=='0')summary.push(value)}if(summary.length)$('#search-request-summary').textContent='Ваш запрос: '+summary.join(' · ')+'. Проверяем предложения операторов.'}
const track=$('#review-track');function scrollReview(delta){const width=$('.review-card').getBoundingClientRect().width+24,end=track.scrollWidth-track.clientWidth;track.scrollTo({left:delta>0&&track.scrollLeft>=end-4?0:delta<0&&track.scrollLeft<=4?end:track.scrollLeft+delta*width,behavior:motion.matches?'instant':'smooth'})}$('#review-prev')?.addEventListener('click',()=>scrollReview(-1));$('#review-next')?.addEventListener('click',()=>scrollReview(1));
const providerTabs=$$('[data-provider-tab]');if(providerTabs.length){const providerPanels=$$('.provider-panel');function selectProvider(key){providerTabs.forEach(tab=>{const active=tab.dataset.providerTab===key;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1});providerPanels.forEach(panel=>panel.hidden=panel.id!==`provider-${key}`)}providerTabs.forEach((tab,index)=>{tab.addEventListener('click',()=>selectProvider(tab.dataset.providerTab));tab.addEventListener('keydown',e=>{let next=index;if(e.key==='ArrowRight')next=(index+1)%providerTabs.length;else if(e.key==='ArrowLeft')next=(index+providerTabs.length-1)%providerTabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=providerTabs.length-1;else return;e.preventDefault();selectProvider(providerTabs[next].dataset.providerTab);providerTabs[next].focus()})});selectProvider(providerTabs[0].dataset.providerTab)}
const video=$('#hero-video');if(video){function initVideo(){if(motion.matches){video.pause();video.removeAttribute('src');return}if(!video.getAttribute('src'))video.src='assets/ocean-waves-720.mp4';video.play().catch(()=>{})}video.addEventListener('error',()=>video.removeAttribute('src'));motion.addEventListener('change',initVideo);initVideo()}
// Fictional fixtures demonstrate filtering and module states; never operator availability.
const fixtures={tours:[['maldives','villas','2027-01-16','Остров и собственная вилла','7 ночей','villa.jpg'],['turkey','family','2027-06-12','Море для всей семьи','10 ночей','turkey.jpg'],['uae','beach','2027-02-20','Город и пляж','7 ночей','uae.jpg'],['thailand','culture','2027-03-14','Город и тропический берег','12 ночей','thailand.jpg']],cruises:[['med','MSC World Europa','2027-05-15','Средиземноморские берега','7 ночей','cruise-light.jpg'],['gulf','MSC Euribia','2027-02-06','Города Персидского залива','7 ночей','uae.jpg'],['med','Costa Toscana','2027-06-19','Лето у Средиземного моря','7 ночей','cruise-light.jpg']],excursions:[['turkey','culture','2027-04-10','Города и пейзажи Турции','8 дней','turkey.jpg'],['thailand','culture','2027-02-18','Знакомство с Таиландом','10 дней','thailand.jpg'],['uae','family','2027-03-20','Открываем ОАЭ всей семьёй','6 дней','uae.jpg']]};
const productPage=$('[data-product-page]');if(productPage){const kind=productPage.dataset.productPage,f=$('#catalog-form'),results=$('#catalog-results');let state=params.get('state'),revision=0;const region=params.get('region')||params.get('country');if([...f.elements.region.options].some(o=>o.value===region))f.elements.region.value=region;if(/^\d{4}-\d{2}-\d{2}$/.test(params.get('date')||''))f.elements.date.value=params.get('date');if(f.elements.ship&&[...f.elements.ship.options].some(o=>o.value===params.get('ship')))f.elements.ship.value=params.get('ship');if(f.elements.format&&['family','villas'].includes(params.get('idea')))f.elements.format.value=params.get('idea');
if(params.has('departure')){const summary=document.createElement('p');summary.className='editor-note';summary.textContent='Ваш запрос: '+[params.get('departure'),params.get('nights'),params.get('adults')?params.get('adults')+' взрослых':null,Number(params.get('children'))>0?params.get('children')+' детей':null].filter(Boolean).join(' · ')+'. В демоподборке фильтруются направление, дата и формат; перелёт и состав туристов потребуют подключения поставщика.';f.after(summary)}
const regionName=k=>countries[k]?.name||({med:'Средиземноморье',gulf:'Персидский залив',asia:'Азия'}[k])||k;const dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'});
function render(){const version=++revision;results.innerHTML='<div class="loading-state" role="status">Подбираем демонстрационные варианты…</div>';setTimeout(()=>{if(version!==revision)return;if(state==='error'){results.innerHTML='<div class="status-panel"><span class="status-label">Демонстрация ошибки</span><h2>Пока не удалось загрузить варианты.</h2><p>Здесь показано состояние недоступности поставщика. Повторите поиск или передайте пожелания менеджеру.</p><button class="button" data-retry>Повторить поиск</button> <button class="text-link" data-lead="Поиск: помощь менеджера">Обсудить путешествие →</button></div>';return}const data=fixtures[kind].filter(r=>(f.elements.region.value==='all'||r[0]===f.elements.region.value)&&(!f.elements.date.value||r[2]>=f.elements.date.value)&&((f.elements.ship||f.elements.format).value==='all'||r[1]===(f.elements.ship||f.elements.format).value));if(state==='empty'||!data.length){results.innerHTML='<div class="status-panel"><span class="status-label">Ничего не найдено в демоподборке</span><h2>Попробуем другие параметры?</h2><p>Измените направление, дату или формат. Менеджер также поможет с индивидуальным запросом.</p><button class="button" data-reset>Показать все варианты</button> <button class="text-link" data-lead="Нет результатов поиска">Запросить подбор →</button></div>';return}results.innerHTML='<div class="catalog-grid">'+data.map(r=>`<article class="catalog-card"><img src="assets/${r[5]}" alt="${esc(regionName(r[0]))} — иллюстрация направления"><div class="catalog-card-copy"><span class="status-label">Тестовый пример · ${esc(regionName(r[0]))}</span><h3>${r[3]}</h3><p>${dateLabel(r[2])} · ${r[4]}${kind==='cruises'?'<br>'+r[1]:''}</p><p>Цена и наличие не определены.</p><button class="button button-outline" data-result="${fixtures[kind].indexOf(r)}">Посмотреть пример ${icon()}</button></div></article>`).join('')+'</div>'},350)}
function reset(){state=null;f.reset();history.replaceState(null,'',location.pathname);render()}f.addEventListener('submit',e=>{e.preventDefault();state=null;const q=new URLSearchParams(new FormData(f));history.replaceState(null,'','?'+q);render()});$('#reset-filters').addEventListener('click',reset);results.addEventListener('click',e=>{if(e.target.closest('[data-retry]')){state=null;history.replaceState(null,'',location.pathname);render()}if(e.target.closest('[data-reset]'))reset();const b=e.target.closest('[data-result]');if(!b)return;const r=fixtures[kind][Number(b.dataset.result)],summary=r[3]+' · '+dateLabel(r[2])+' · '+r[4];content(`<img class="dialog-cover" src="assets/${r[5]}" alt="Иллюстрация направления"><p class="eyebrow">Тестовый пример</p><h2 id="content-title">${r[3]}</h2><p>${esc(regionName(r[0]))} · ${dateLabel(r[2])} · ${r[4]}</p><p>Это образец карточки для согласования интерфейса. Маршрут, даты и состав услуг не являются предложением оператора. После подключения модуля здесь появятся реальные детали и цена.</p><button class="button" data-lead="${esc('Демо: '+summary)}">Обсудить похожее путешествие ${icon()}</button>`)});render()}
if($('#office-map')){$$('[data-office]').forEach(b=>b.addEventListener('click',()=>{const place=b.dataset.office==='mytishchi'?'Мытищи проспект Астрахова 10':'Калининград Черняховского 20';$('#office-map').src='https://yandex.ru/map-widget/v1/?text='+encodeURIComponent(place)+'&z=16';$('#office-map').title='Карта: '+place;$('#office-map-link').href='https://yandex.ru/maps/?text='+encodeURIComponent(place);$('#office-map').scrollIntoView({behavior:motion.matches?'instant':'smooth',block:'center'})}))}
if($('#share-copy')){const url=location.href,title=document.title;$('#share-tg').href='https://t.me/share/url?url='+encodeURIComponent(url)+'&text='+encodeURIComponent(title);$('#share-vk').href='https://vk.com/share.php?url='+encodeURIComponent(url);$('#share-copy').addEventListener('click',async e=>{const button=e.currentTarget;try{await navigator.clipboard.writeText(url);button.textContent='Ссылка скопирована'}catch{content('<h2 id="content-title">Ссылка на статью</h2><p>Скопируйте адрес из строки браузера.</p><p class="share-url">'+esc(url)+'</p>')}})}




